install:
- choco install cloc --no-progress
- "cloc --vcs git --exclude-dir Resources,store,test,UWP,Properties --include-lang C#,JavaScript,TypeScript,PowerShell"
#  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
#  - appveyor DownloadFile https://aka.ms/vs/15/release/vs_community.exe
#  - vs_community.exe update --wait --quiet --norestart --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
before_build:
  - nuget restore
  - IF DEFINED keystore_dec_secret nuget install secure-file -ExcludeVersion
  - IF DEFINED google_services_dec_secret secure-file\tools\secure-file -decrypt src\Android\google-services.json.enc -secret %google_services_dec_secret%
after_build:
  - ps: IF($env:keystore_dec_secret) { .\src\Android\ci-build-apks.ps1 }
on_success:
  - IF DEFINED play_dec_secret secure-file\tools\secure-file -decrypt store\google\Publisher\play_creds.json.enc -secret %play_dec_secret%
  - IF DEFINED play_dec_secret dotnet store\google\Publisher\bin\Release\netcoreapp2.0\Publisher.dll %APPVEYOR_BUILD_FOLDER%\store\google\Publisher\play_creds.json %APPVEYOR_BUILD_FOLDER%\com.x8bit.bitwarden-%APPVEYOR_BUILD_NUMBER%.apk alpha
artifacts:
  - path: com.x8bit.bitwarden-%APPVEYOR_BUILD_NUMBER%.apk
  - path: com.x8bit.bitwarden-fdroid-%APPVEYOR_BUILD_NUMBER%.apk
branches:
  except:
    - l10n_master
skip_tags: true
configuration: Release
image: Visual Studio 2017
